92 feature/profile component
chas-academy/Cobalt-client pull request #113
Opened 2018-04-26 12:49 UTC by Ciavarella

Added one more size to the Avatar component, XL use `<Avatar size="xl" />` to use the xl size.

Added titles to the dashboard based on what you click on the dashboard.

Added profile component and profile view on dashboard. This will add a avatar and you can change password, email and name. Request to backend not done yet, it only console logs it.

closes #92

2018-04-30 08:14 UTC, robertjarske commented on src/Components/Profile.js
> +            {/** SPACING!!!! **/}
Please remove comment

2018-04-30 08:15 UTC, robertjarske approved these changes

2018-05-02 07:56 UTC, joakimunge commented
Some thoughts on this:

![1](https://user-images.githubusercontent.com/24225542/39511745-d0303788-4dee-11e8-988e-511037e878e4.PNG)
![2](https://user-images.githubusercontent.com/24225542/39511753-d3bc8078-4dee-11e8-9c5d-60b65fb933aa.PNG)

- Could we maybe align the boxes to the left, like the rest of the dashboard content? (See sessions)
- The boxes seem unnecessarily big. Looking at you password box!
- Can we remove the hover from the boxes? They have no interaction

2018-05-02 08:00 UTC, joakimunge requested changes
See suggestions above.

2018-05-07 11:29 UTC, joakimunge approved these changes

2018-05-07 11:29 UTC, merged