Removed things that is not used
chas-academy/Cobalt-client pull request #203
Opened 2018-05-14 09:44 UTC by Ciavarella

In createsession, commented out "Max attendees", "Allow comments" & "Show average as percentage". They are not used. Commented out so they can be implemented in the future.

Edited "Upgrade plan" in dashboard to instead be "Workspaces".

closes #201

2018-05-14 12:39 UTC, joakimunge requested changes
Can we swap the icon for "Workspaces" in Navigation? The pricetag isn't really relevant anymore

2018-05-14 13:53 UTC, robertjarske approved these changes

2018-05-21 09:58 UTC, lessp approved these changes

2018-05-21 09:59 UTC, joakimunge approved these changes

2018-05-21 09:59 UTC, merged