feature/session wizard
chas-academy/Cobalt-client pull request #94
Opened 2018-04-24 08:32 UTC by Andreas-sjolund-chas

2018-04-24 14:37 UTC, robertjarske requested changes

2018-04-24 14:37 UTC, robertjarske commented on src/Components/CreateSession/End.js
> +      Have a greate session!
What is greate? What a GREAT word ;)

2018-04-25 08:22 UTC, robertjarske approved these changes

2018-04-25 08:51 UTC, lessp requested changes

2018-04-25 08:51 UTC, lessp commented on src/Components/Wizard.js
> +                : "NEXT - " + (this.state.currentPage + 1) + " / 3"}
Could use children.length or something in order to calculate the number of pages.

2018-04-25 08:51 UTC, lessp commented on src/Components/Wizard.js
> +  /** TODO: Set up redux with each input from each step so we can handle all the settings at once */
Focus on just being able to pass the data from the Wizard up to "something" else.

2018-04-25 11:53 UTC, lessp approved these changes

2018-04-26 15:34 UTC, Ciavarella approved these changes
Looks nice!

2018-04-27 08:58 UTC, merged